In [2]:
import numpy as np
a = np.array([3,4,5])
b = np.array([1,3,6])
print(np.dot(a,b))

45


In [5]:
m1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
m1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
m1.shape

(3, 3)

In [8]:
m2 = np.matrix([[2],[3],[4]])
print(m1*m2)

[[20]
 [47]
 [74]]


In [9]:
mT = np.transpose(m1)

In [10]:
mT

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [1]:
from numpy import linalg as LA

In [3]:
l1 = np.matrix([[1,3,1],[2,2,1],[3,5,3]])

In [4]:
l1

matrix([[1, 3, 1],
        [2, 2, 1],
        [3, 5, 3]])

In [5]:
LA.matrix_rank(l1)

3

In [6]:
np.linalg.matrix_rank(l1)

3