In [1]:
import numpy as np
a1 = np.array([2,1,3,4])
a2 = np.array([[2,1,4],[2,5,4],[2,6,3]])
a3 = np.array([[[2,1,4],[2,1,4],[2,1,4]],[[2,1,4],[2,1,4],[2,1,4]],[[2,1,4],[2,1,4],[2,1,4]]])

a4 = np.arange(10,50)
a5 = np.arange(10)
a6 = np.arange(.5,5,.25) #.25 distance

a7 = np.linspace(3,8,9) # split into 9 steps

ao1 = np.ones((2,2)) # fill marix with one

e1 = np.eye(4)

print(a4)
print(e1)
print(ao1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1.]
 [1. 1.]]


In [2]:

ran1 = np.random.random((4,4)) #random matrix
print(ran1)
print(ran1.ndim) #print matrix dimension
print(ran1.shape)
print(ran1.size)
print(ran1.dtype)
print(a1.reshape(2,2)) #make smaller matrix into new dimension
print(a2)
print('------------')
print(a2[2:3])


s1 = np.arange(5,15)
print(s1)
print(s1.max())
print(s1.min())
print(s1.cumsum())

x1 = np.linspace(0,180,10)
print(np.sin(x1))

x2 = np.arange(9).reshape(3,3)
print(x2)

#multiplication of matrix

x3 = np.arange(6).reshape(3,2)
x4 = np.arange(10,16).reshape(2,3)
print(x3.dot(x4))


[[0.06593745 0.12624763 0.37671096 0.06665947]
 [0.10075024 0.03815777 0.19396562 0.69909737]
 [0.76356935 0.56849491 0.279947   0.45804901]
 [0.70015817 0.89395387 0.72875507 0.05856874]]
2
(4, 4)
16
float64
[[2 1]
 [3 4]]
[[2 1 4]
 [2 5 4]
 [2 6 3]]
------------
[[2 6 3]]
[ 5  6  7  8  9 10 11 12 13 14]
14
5
[ 5 11 18 26 35 45 56 68 81 95]
[ 0.          0.91294525  0.74511316 -0.30481062 -0.99388865 -0.50636564
  0.58061118  0.98023966  0.21942526 -0.80115264]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 13  14  15]
 [ 59  64  69]
 [105 114 123]]


In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
print(type(s1))

<class 'numpy.ndarray'>


In [13]:
c = range(10000)
%timeit [i**3 for i in c] # normal list

11 ms ± 1.25 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
c_np = np.arange(10000)        #numpy list
%timeit [i**3 for i in c_np]

5.94 ms ± 438 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [16]:
np.diag([1,2,3,4,5,6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [25]:
np.random.random([3,2])

array([[0.15632574, 0.41331654],
       [0.42651332, 0.27111208],
       [0.86438803, 0.51238468]])

In [29]:
s1.itemsize

4

In [33]:
r1 = np.arange(9).reshape(3,3)
print(r1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
r1[2:5]

array([[6, 7, 8]])

In [35]:
r1[0::2]

array([[0, 1, 2],
       [6, 7, 8]])

In [36]:
r1[(r1>2) & (r1<7) ]

array([3, 4, 5, 6])

In [4]:
import numpy as np
t1 = np.arange(10)
t2 = t1

In [5]:
np.shares_memory(t1,t2)

True

In [6]:
t3 = t1.copy()

In [7]:
np.shares_memory(t1,t3)

False